import React,{useEffect,useMemo,useState}from'react';
import{SafeAreaView,View,Text,TouchableOpacity,FlatList,ScrollView,StyleSheet,TextInput,Alert}from'react-native';
import AsyncStorage from'@react-native-async-storage/async-storage';
import{StatusBar}from'expo-status-bar';

const EVENTS=[
{id:'1',title:'AI & Coding Workshop',club:'Tech Club',category:'Technology',date:'20 Oct 2026, 2:00 PM',location:'Innovation Lab',slots:25,type:'Workshop',description:'Learn practical AI and coding skills with other students. Bring your laptop and join an interactive hands-on session.'},
{id:'2',title:'Career Networking Day',club:'Career Club',category:'Career',date:'25 Oct 2026, 12:00 PM',location:'Main Hall',slots:80,type:'Networking',description:'Meet employers, alumni and students and discover internships, graduate opportunities and career advice.'},
{id:'3',title:'Campus Football Tournament',club:'Sports Club',category:'Sports',date:'1 Nov 2026, 10:00 AM',location:'University Stadium',slots:40,type:'Sports',description:'Join the campus football tournament, meet new people and support your university teams.'},
{id:'4',title:'Community Volunteer Day',club:'Volunteer Club',category:'Volunteering',date:'8 Nov 2026, 9:00 AM',location:'Student Center',slots:50,type:'Volunteering',description:'Take part in a student-led community volunteering day and help make a positive difference.'},
{id:'5',title:'Creative Arts Evening',club:'Arts Club',category:'Arts',date:'15 Nov 2026, 6:00 PM',location:'Arts Building',slots:35,type:'Arts',description:'An evening of music, photography, design and student creativity.'}
];

const GUEST={name:'Campus Guest',email:'guest@campusconnect.local',role:'Student',bio:'Using CampusConnect without an account.'};

function Button({title,onPress,secondary=false,disabled=false}){return <TouchableOpacity disabled={disabled} onPress={onPress} style={[s.button,secondary&&s.secondary,disabled&&s.disabled]}><Text style={[s.buttonText,secondary&&s.secondaryText]}>{title}</Text></TouchableOpacity>}

function Events({open}){const[q,setQ]=useState(''),[category,setCategory]=useState('All');const filtered=useMemo(()=>EVENTS.filter(e=>(category==='All'||e.category===category)&&(`${e.title} ${e.club} ${e.description}`).toLowerCase().includes(q.toLowerCase())),[q,category]);return <View style={s.screen}><Text style={s.title}>Upcoming Events</Text><Text style={s.subtitle}>Discover university events, clubs and activities.</Text><TextInput value={q} onChangeText={setQ} placeholder="Search events or clubs" style={s.input}/><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{marginBottom:12}}>{['All','Technology','Career','Sports','Volunteering','Arts'].map(c=><TouchableOpacity key={c} onPress={()=>setCategory(c)} style={[s.chip,category===c&&s.chipActive]}><Text style={category===c?s.chipTextActive:s.chipText}>{c}</Text></TouchableOpacity>)}</ScrollView><FlatList data={filtered} keyExtractor={e=>e.id} contentContainerStyle={{paddingBottom:100}} ListEmptyComponent={<Text style={s.empty}>No events found.</Text>} renderItem={({item})=><TouchableOpacity style={s.card} onPress={()=>open(item)}><Text style={s.cardTitle}>{item.title}</Text><Text style={s.muted}>{item.club} • {item.category}</Text><Text style={s.body}>{item.date}</Text><Text style={s.body}>{item.location}</Text><Text style={s.slots}>{item.slots} places remaining</Text></TouchableOpacity>}/></View>}

function Detail({event,back}){const[registered,setRegistered]=useState(false);useEffect(()=>{AsyncStorage.getItem('cc_rsvps').then(x=>{if(x)setRegistered(JSON.parse(x).includes(event.id))})},[event.id]);const rsvp=async()=>{const raw=await AsyncStorage.getItem('cc_rsvps');const ids=raw?JSON.parse(raw):[];if(!ids.includes(event.id))ids.push(event.id);await AsyncStorage.setItem('cc_rsvps',JSON.stringify(ids));setRegistered(true);Alert.alert('RSVP confirmed','Your place has been saved on this device.');};return <ScrollView contentContainerStyle={s.container}><TouchableOpacity onPress={back}><Text style={s.back}>‹ Back to events</Text></TouchableOpacity><Text style={s.title}>{event.title}</Text><Text style={s.badge}>{event.category} • {event.type}</Text><Text style={s.body}>{event.description}</Text><View style={s.info}><Text style={s.label}>Club</Text><Text style={s.body}>{event.club}</Text><Text style={s.label}>When</Text><Text style={s.body}>{event.date}</Text><Text style={s.label}>Where</Text><Text style={s.body}>{event.location}</Text><Text style={s.label}>Places</Text><Text style={s.body}>{event.slots} remaining</Text></View><Button title={registered?'Already registered':'RSVP for this event'} onPress={rsvp} disabled={registered}/><Button title="Back to events" secondary onPress={back}/></ScrollView>}

function RSVPs(){const[rows,setRows]=useState([]);const load=()=>AsyncStorage.getItem('cc_rsvps').then(x=>{const ids=x?JSON.parse(x):[];setRows(EVENTS.filter(e=>ids.includes(e.id)))});useEffect(()=>{load()},[]);const cancel=id=>Alert.alert('Cancel RSVP','Remove this RSVP?', [{text:'Keep',style:'cancel'},{text:'Cancel',style:'destructive',onPress:async()=>{const raw=await AsyncStorage.getItem('cc_rsvps');const ids=raw?JSON.parse(raw):[];await AsyncStorage.setItem('cc_rsvps',JSON.stringify(ids.filter(x=>x!==id)));load()}}]);return <View style={s.screen}><Text style={s.title}>My RSVPs</Text><Text style={s.subtitle}>Your saved event registrations.</Text><FlatList data={rows} keyExtractor={e=>e.id} contentContainerStyle={{paddingBottom:100}} ListEmptyComponent={<Text style={s.empty}>You have no RSVPs yet.</Text>} renderItem={({item})=><View style={s.card}><Text style={s.cardTitle}>{item.title}</Text><Text style={s.muted}>{item.club}</Text><Text>{item.date}</Text><Button title="Cancel RSVP" secondary onPress={()=>cancel(item.id)}/></View>}/></View>}

function Profile(){return <ScrollView contentContainerStyle={s.container}><Text style={s.title}>Profile</Text><View style={s.profile}><Text style={s.avatar}>C</Text><Text style={s.cardTitle}>{GUEST.name}</Text><Text style={s.muted}>{GUEST.email}</Text><Text style={s.body}>Role: {GUEST.role}</Text><Text style={s.body}>{GUEST.bio}</Text></View><Text style={s.section}>Guest access</Text><Text style={s.body}>You can browse events and save RSVPs without creating an account. Your RSVPs are stored locally on this device.</Text><Text style={s.note}>An account can be connected later when the backend is ready.</Text></ScrollView>}

export default function App(){const[tab,setTab]=useState('events'),[detail,setDetail]=useState(null);if(detail)return <SafeAreaView style={s.safe}><Detail event={detail} back={()=>setDetail(null)}/><StatusBar style="dark"/></SafeAreaView>;return <SafeAreaView style={s.safe}><View style={{flex:1}}>{tab==='events'?<Events open={setDetail}/>:tab==='rsvps'?<RSVPs/>:<Profile/>}</View><View style={s.nav}><TouchableOpacity onPress={()=>setTab('events')}><Text style={tab==='events'?s.navActive:s.navText}>Events</Text></TouchableOpacity><TouchableOpacity onPress={()=>setTab('rsvps')}><Text style={tab==='rsvps'?s.navActive:s.navText}>My RSVPs</Text></TouchableOpacity><TouchableOpacity onPress={()=>setTab('profile')}><Text style={tab==='profile'?s.navActive:s.navText}>Profile</Text></TouchableOpacity></View><StatusBar style="dark"/></SafeAreaView>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f7f8fb'},screen:{flex:1,padding:20},container:{padding:20,paddingBottom:100},title:{fontSize:30,fontWeight:'800',marginBottom:8},subtitle:{fontSize:16,color:'#666',marginBottom:18},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#ddd',borderRadius:12,padding:14,fontSize:16,marginBottom:12},chip:{paddingVertical:9,paddingHorizontal:14,borderRadius:20,borderWidth:1,borderColor:'#ddd',backgroundColor:'#fff',marginRight:8},chipActive:{backgroundColor:'#111827',borderColor:'#111827'},chipText:{color:'#333'},chipTextActive:{color:'#fff',fontWeight:'700'},card:{backgroundColor:'#fff',padding:17,borderRadius:15,marginBottom:12,borderWidth:1,borderColor:'#e5e7eb'},cardTitle:{fontSize:19,fontWeight:'800',marginBottom:6},muted:{color:'#666',marginBottom:7},body:{fontSize:16,lineHeight:24,marginBottom:10},slots:{fontWeight:'800',marginTop:5},button:{backgroundColor:'#111827',paddingVertical:14,paddingHorizontal:16,borderRadius:11,marginBottom:11,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'800'},secondary:{backgroundColor:'#fff',borderWidth:1,borderColor:'#ccc'},secondaryText:{color:'#111827'},disabled:{opacity:.5},empty:{textAlign:'center',marginTop:45,color:'#666',fontSize:16},back:{fontSize:16,fontWeight:'700',marginBottom:20},badge:{alignSelf:'flex-start',backgroundColor:'#e5e7eb',padding:8,borderRadius:8,fontWeight:'700',marginBottom:18},info:{backgroundColor:'#fff',padding:17,borderRadius:14,marginBottom:18},label:{fontWeight:'800',marginTop:5,marginBottom:2},profile:{backgroundColor:'#fff',padding:22,borderRadius:16,alignItems:'center',marginBottom:20},avatar:{width:72,height:72,borderRadius:36,backgroundColor:'#111827',color:'#fff',textAlign:'center',paddingTop:20,fontSize:28,fontWeight:'800',marginBottom:12},section:{fontSize:21,fontWeight:'800',marginBottom:10},note:{backgroundColor:'#e8f4ff',padding:14,borderRadius:10,lineHeight:22},nav:{height:65,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#ddd',flexDirection:'row',justifyContent:'space-around',alignItems:'center'},navText:{color:'#666',fontWeight:'600'},navActive:{color:'#111827',fontWeight:'900'}});
